---
dist: focal
os: linux
language: go
go: 1.18

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - TF_VERSION='1.2.9'
  - TF_IN_AUTOMATION=true

# execute tests
install:
- sudo wget "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
- sudo unzip "terraform_${TF_VERSION}_linux_amd64.zip" -d /usr/bin/
- sudo apt-get update && sudo apt-get install -y --no-install-recommends ansible

before_script:
- terraform init -backend=false -no-color
- cd acceptance && terraform init -no-color && cd ..

script:
- terraform validate -no-color
- terraform fmt -diff -check -no-color
- cd acceptance && go get -t github.com/mschuchard/terraform-local-ansible-inv && go test -v
