---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TF_IN_AUTOMATION: 'true'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        tf_version: ['1.1.8']
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name:
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ matrix.tf_version }}
    - name: initialize terraform module
      run: terraform init -backend=false -no-color
    - name: initialize acceptance test
      run: cd acceptance && terraform init -no-color
    - name: install ansible
      run: pip install ansible
    - name: validate terraform module
      run: terraform validate -no-color
    - name: verify proper formatting
      run: terraform fmt -diff -check -no-color
    - name: acceptance test terraform module
      run: cd acceptance && terraform apply -input=false -no-color -auto-approve
