---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '*.tf'
    - 'templates/*'
    - 'acceptance/*'
  pull_request:
    branches: [master]
    paths:
    - '*.tf'
    - 'templates/*'
    - 'acceptance/*'

env:
  TF_IN_AUTOMATION: 'true'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        container: ['matthewschuchard/terraform-ansible']
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: initialize terraform module
      run: terraform init -backend=false -no-color
    - name: initialize acceptance test
      run: cd acceptance && terraform init -no-color
    - name: validate terraform module
      run: terraform validate -no-color
    - name: verify proper formatting
      run: terraform fmt -diff -check -no-color
    - name: acceptance test terraform module
      run: cd acceptance && terraform apply -input=false -no-color -auto-approve
    # TODO: deactivated temporarily because GH actions causing issue with JSON parsing in terratest go code
    #- name: acceptance test terraform module
    #  run: cd acceptance && go get -t github.com/mschuchard/terraform-local-ansible-inv && go test -v
